
server:
  port: 8070
spring:

  cache:
    type: caffeine
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  data:
    web:
      pageable:
        default-page-size: 5
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    url: jdbc:postgresql://localhost/boostdb
    username: postgres
  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.PostgreSQL9Dialect
        dialect: tech.artcoded.boost.common.config.CustomPostgreSqlDialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  resources:
    add-mappings: true # remove in case the frontend is running separately
jackson:
  serialization:
    FAIL_ON_EMPTY_BEANS: false
application:
  title: Boost!
  version: v0.0.1-SNAPSHOT
boost:
  event:
    topic: boostevent
  upload:
    dir: /tmp/boost
jwt:
  audience: authenticated-app
  expire:
    after: 600000 # 10 min
  header: Authorization
  issuer: authentication-server
  prefix: Bearer
  secret: Zq4t7w!z%C*F-JaNdRgUkXp2s5u8x/A?D(G+KbPeShVmYq3t6w9y$B&E)H@McQfT
  type: jwt

fixture:
  books:
    size: 2
    delete-at-start: true